[deps]
Clang = "40e3b903-d033-50b4-a0cc-940c62c95e31"
JLLPrefixes = "afc68a34-7891-4c5a-9da1-1c62935e7b0d"
LibAwsAuth = "e028494f-7ddb-47cd-bd9c-7e7578dea4c5"
LibAwsCal = "ef519ef6-af43-41a0-8ac4-eb81328190af"
LibAwsChecksums = "332a3e40-df62-419b-9f04-2cb73588ccaf"
LibAwsCommon = "c6e421ba-b5f8-4792-a1c4-42948de3ed9d"
LibAwsCompression = "51c8708f-2dd9-446d-a0d4-ba9f49ba4b23"
LibAwsHTTP = "ce851869-0d7a-41e7-95ef-2d4cb63876dd"
LibAwsIO = "a5388770-19df-4151-b103-3d71de896ddf"
LibAwsSdkutils = "c5f27dc9-c37b-4573-9b6c-b90055172160"
aws_c_auth_jll = "2b3700d1-4306-52e2-a478-c162f0c514be"
aws_c_cal_jll = "70f11efc-bab2-57f1-b0f3-22aad4e67c4b"
aws_c_common_jll = "73048d1d-b8c4-5092-a58d-866c5e8d1e50"
aws_c_compression_jll = "73a04cd5-f3d7-5bac-9290-e8adb709f224"
aws_c_http_jll = "3254fc65-9028-534d-aa9d-d76d128babc6"
aws_c_io_jll = "13c41daa-f319-5298-b5eb-5754e0170d52"
aws_c_s3_jll = "bd1f34fb-993f-5903-a121-aaf302eed6d4"
aws_c_sdkutils_jll = "1282aa60-004d-510b-9f52-12498d409daa"
aws_checksums_jll = "b2a88e68-78e7-5e94-8c20-c02986ec140e"

[compat]
Clang = "0.18.3,0.19"
JLLPrefixes = "0.3,0.4"
aws_c_s3_jll = "=0.5.7"
